spring:
  application:
    name: Team Task Manager

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT configuration
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000 # 1 day in milliseconds

# Frontend API URL
frontend:
  url: http://localhost:5173
