spring:
  application:
    name: Team Task Manager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
